"use server";
import {redirect} from "next/navigation";
import {revalidatePath} from "next/cache";
import {getDb,newId} from "@/server/db";
import {requireSession} from "@/features/auth/session";
import {requiredText} from "@/features/shared/validation";
export type TaskState={errors?:Record<string,string>};
export async function createTask(_:TaskState,form:FormData):Promise<TaskState>{const user=await requireSession();const title=requiredText(form,"title",3,180),description=requiredText(form,"description",3,2000);const errors:Record<string,string>={};if(title.error)errors.title=title.error;if(description.error)errors.description=description.error;const priority=String(form.get("priority")??"medium"),deadline=String(form.get("deadline")??""),assigneeType=String(form.get("assignee_type")??"human"),assignee=String(form.get("assignee")??""),client=String(form.get("client")??"")||null;if(!["low","medium","high","urgent"].includes(priority))errors.priority="Choose a valid priority";if(!deadline)errors.deadline="Deadline is required";if(!assignee)errors.assignee="Choose an assignee";if(Object.keys(errors).length)return{errors};const id=newId("task"),db=getDb();db.prepare("INSERT INTO tasks (id,title,description,priority,status,deadline,created_by,assigned_user_id,assigned_ai_id,client_id) VALUES (?,?,?,?,?,?,?,?,?,?)").run(id,title.value,description.value,priority,"todo",deadline,user.id,assigneeType==="human"?assignee:null,assigneeType==="ai"?assignee:null,client);db.prepare("INSERT INTO activities (id,actor_type,actor_id,action,entity_type,entity_id,metadata) VALUES (?,?,?,?,?,?,?)").run(newId("activity"),"user",user.id,"created task","task",id,"{}");if(assigneeType==="human")db.prepare("INSERT INTO notifications (id,user_id,type,title,message,entity_type,entity_id) VALUES (?,?,?,?,?,?,?)").run(newId("notification"),assignee,"task_assigned","New task assigned",title.value,"task",id);revalidatePath("/tasks");revalidatePath("/dashboard");redirect("/tasks?created=1")}
export async function updateTaskStatus(form:FormData){await requireSession();const id=String(form.get("id")??""),status=String(form.get("status")??"");if(!["todo","in_progress","review","done","rejected","escalated"].includes(status))return;getDb().prepare("UPDATE tasks SET status=?,completed_at=CASE WHEN ?='done' THEN CURRENT_TIMESTAMP ELSE NULL END,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,status,id);revalidatePath("/tasks");revalidatePath("/dashboard")}
