import Link from "next/link";
import {IconArrowUpRight,IconUserPlus} from "@tabler/icons-react";
import {ClientOnboardingForm} from "@/components/business-operation-forms";
import {PageHeader} from "@/components/page-header";
import {listTimeline} from "@/server/repositories/business-operations";

export default async function ClientOnboardingPage({searchParams}:{searchParams:Promise<{created?:string}>}){
 const params=await searchParams,timeline=listTimeline("client").slice(0,8);
 return <div className="page narrow-page">
  <PageHeader eyebrow="CLIENT ONBOARDING" title="Onboarding Wizard" subtitle="Capture client, company, identity, service, source, priority and risk level into a real client profile." action={<Link className="secondary-button" href="/crm">Open CRM <IconArrowUpRight size={14}/></Link>}/>
  {params.created&&<div className="success-banner">Client profile created: <strong>{params.created}</strong></div>}
  <section className="panel"><div className="panel-head"><div><h2>New client intake</h2><p>Submitted onboarding creates client, company, queue, activity and audit records.</p></div><IconUserPlus size={18}/></div><ClientOnboardingForm/></section>
  <section className="panel recent"><div className="panel-head"><div><h2>Recent onboarding activity</h2><p>Timeline events generated by client intake</p></div></div><div className="activity-list">{timeline.map(item=><div className="activity-item" key={item.id}><i/><div><strong>{item.actor}</strong><p>{item.action} - {item.entity_id}</p></div><time>{new Date(item.created_at).toLocaleDateString("en-AE",{day:"numeric",month:"short"})}</time></div>)}</div></section>
 </div>
}
