export const enabledCountryOptions = ["UAE", "Saudi Arabia", "UK", "Canada", "India"] as const;

export const coreServiceOptions = [
  "Company Formation",
  "Visa Services",
  "Banking Assistance",
  "Corporate Tax",
  "VAT",
  "Accounting",
  "Compliance",
  "Private Client",
  "Wealth Structuring",
  "Document Clearing",
  "PRO Services",
] as const;

export const aiPrincipleKeys = [
  "assistNotReplace",
  "recommendationsRequireExplanation",
  "sensitiveDecisionsRequireHumanApproval",
  "aiGeneratedContentLabelled",
  "humanAccountabilityFinal",
] as const;

export type AiPrincipleKey = (typeof aiPrincipleKeys)[number];

export type CompanyProfile = {
  basic: {
    companyName: string;
    legalName: string;
    displayName: string;
    tagline: string;
    industry: string;
    headquartersCountry: string;
    headquartersCity: string;
    timeZone: string;
    defaultCurrency: string;
    defaultLanguage: string;
    secondaryLanguage: string;
    dateFormat: string;
    numberFormat: string;
  };
  contact: {
    website: string;
    generalEmail: string;
    supportEmail: string;
    phone: string;
    whatsApp: string;
    officeAddress: string;
    googleMapsLink: string;
    businessHours: string;
  };
  branding: {
    logoUploadPlaceholder: string;
    darkLogoPlaceholder: string;
    lightLogoPlaceholder: string;
    faviconPlaceholder: string;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    backgroundColor: string;
  };
  identity: {
    about: string;
    internalMission: string;
    visionStatement: string;
    customerPromise: string;
    coreValues: string;
  };
  enabledCountries: string[];
  coreServices: string[];
  aiOperatingPrinciples: Record<AiPrincipleKey, string>;
};

export const defaultCompanyProfile: CompanyProfile = {
  basic: {
    companyName: "Morifar Group",
    legalName: "Morifar Group",
    displayName: "Morifar",
    tagline: "AI-Powered Private Client & Corporate Services",
    industry: "Corporate Services",
    headquartersCountry: "United Arab Emirates",
    headquartersCity: "Dubai",
    timeZone: "Asia/Dubai",
    defaultCurrency: "AED",
    defaultLanguage: "English",
    secondaryLanguage: "Arabic",
    dateFormat: "DD/MM/YYYY",
    numberFormat: "1,234.56",
  },
  contact: {
    website: "https://morifar.com",
    generalEmail: "hello@morifar.com",
    supportEmail: "support@morifar.com",
    phone: "+971",
    whatsApp: "+971",
    officeAddress: "Dubai, United Arab Emirates",
    googleMapsLink: "",
    businessHours: "Monday to Friday, 9:00 AM - 6:00 PM GST",
  },
  branding: {
    logoUploadPlaceholder: "Logo upload reserved for storage integration",
    darkLogoPlaceholder: "Dark logo upload reserved for storage integration",
    lightLogoPlaceholder: "Light logo upload reserved for storage integration",
    faviconPlaceholder: "Favicon upload reserved for storage integration",
    primaryColor: "#07111f",
    secondaryColor: "#101f33",
    accentColor: "#caa66a",
    backgroundColor: "#0b1728",
  },
  identity: {
    about:
      "Morifar is an AI-first corporate services and private client platform headquartered in Dubai. The company helps entrepreneurs, investors, families, and businesses establish, manage, and grow their presence across multiple jurisdictions through technology-assisted professional services.",
    internalMission:
      "Simplifying global business, immigration, wealth, and compliance through AI-assisted professional services.",
    visionStatement: "To build the world's most trusted AI-powered private client operating platform.",
    customerPromise:
      "Every recommendation generated by Morifar AI must support-not replace-the judgement of qualified professionals. AI assists, humans remain accountable.",
    coreValues:
      "Integrity\nConfidentiality\nProfessionalism\nSpeed\nCompliance\nTransparency\nContinuous Improvement",
  },
  enabledCountries: [...enabledCountryOptions],
  coreServices: [...coreServiceOptions],
  aiOperatingPrinciples: {
    assistNotReplace: "AI must assist, not replace professionals.",
    recommendationsRequireExplanation: "AI recommendations require explanation.",
    sensitiveDecisionsRequireHumanApproval: "Sensitive decisions require human approval.",
    aiGeneratedContentLabelled: "AI-generated content must be clearly labelled.",
    humanAccountabilityFinal: "Human accountability remains final.",
  },
};

