"use server";
import {redirect} from "next/navigation";
import {revalidatePath} from "next/cache";
import {getDb,newId} from "@/server/db";
import {requireSession} from "@/features/auth/session";
import {routeAi} from "@/server/repositories/ai";
import {requiredText,validEmail} from "@/features/shared/validation";
export type LeadState={errors?:Record<string,string>};
export async function createLead(_:LeadState,form:FormData):Promise<LeadState>{const user=await requireSession();const fields=["name","email","whatsapp","country","service","budget","timeline"] as const;const values:Record<string,string>={},errors:Record<string,string>={};fields.forEach(key=>{const result=requiredText(form,key,1,250);values[key]=result.value;if(result.error)errors[key]=result.error});if(values.email&&!validEmail(values.email))errors.email="Enter a valid email address";if(Object.keys(errors).length)return{errors};const ai=routeAi(values.country,values.service);if(!ai)return{errors:{service:"No AI professional is available for this enquiry"}};const id=newId("lead"),notes=String(form.get("notes")??"").trim().slice(0,2000);const db=getDb();db.prepare("INSERT INTO leads (id,name,email,whatsapp,country,service,budget,timeline,notes,assigned_consultant_id,assigned_ai_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)").run(id,values.name,values.email,values.whatsapp,values.country,values.service,values.budget,values.timeline,notes,user.id,ai.id);db.prepare("INSERT INTO activities (id,actor_type,actor_id,action,entity_type,entity_id,metadata) VALUES (?,?,?,?,?,?,?)").run(newId("activity"),"user",user.id,"created and routed lead","lead",id,JSON.stringify({assignedAi:ai.name}));db.prepare("INSERT INTO notifications (id,user_id,type,title,message,entity_type,entity_id) VALUES (?,?,?,?,?,?,?)").run(newId("notification"),user.id,"new_lead","New lead routed",`${values.name} was assigned to ${ai.name}`,"lead",id);revalidatePath("/leads");revalidatePath("/dashboard");redirect(`/leads?created=${encodeURIComponent(values.name)}`)}
