import Link from "next/link";
import {IconFilter,IconGitBranch} from "@tabler/icons-react";
import {PageHeader} from "@/components/page-header";
import {updateQueueItem} from "@/features/business-operations/actions";
import {businessFormOptions,listDepartmentQueueItems} from "@/server/repositories/business-operations";

export default async function DepartmentQueuesPage({searchParams}:{searchParams:Promise<{department?:string;status?:string;q?:string}>}){
 const params=await searchParams,department=params.department??"all",status=params.status??"all",q=params.q??"",options=businessFormOptions(),items=listDepartmentQueueItems({department,status,q});
 return <div className="page">
  <PageHeader eyebrow="DEPARTMENT QUEUES" title="Department Queues" subtitle="Formation, operations, sales, compliance and AI work queues with filtering, assignment and priority."/>
  <section className="panel"><form className="lead-toolbar"><div className="field-search"><input name="q" defaultValue={q} placeholder="Search queues, entity type or priority" aria-label="Search department queues"/></div><div className="toolbar-actions"><select name="department" defaultValue={department} aria-label="Department filter"><option value="all">All departments</option>{options.departments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="status" defaultValue={status} aria-label="Queue status filter"><option value="all">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="done">Done</option></select><button><IconFilter size={16}/>Apply</button></div></form></section>
  <section className="task-board ops-queue-board">{["urgent","high","medium","low"].map(priority=><div className="task-column" key={priority}><header><span>{priority}</span><b>{items.filter(item=>item.priority===priority).length}</b></header>{items.filter(item=>item.priority===priority).map(item=><article className="task-card" key={item.id}><div className="task-card-top"><span className={`priority ${item.priority}`}>{item.priority}</span><small>{item.status}</small></div><h3>{item.title}</h3><p>{item.department_name} - {item.entity_type} {item.entity_id}</p><div className="task-assignee"><div className={item.assigned_ai?"ai-avatar":"human-avatar"}>{(item.assigned_ai??item.assigned_user??"?").split(" ").map(x=>x[0]).join("").slice(0,2)}</div><span>{item.assigned_ai??item.assigned_user??"Unassigned"}</span></div><form action={updateQueueItem} className="status-form"><input type="hidden" name="id" value={item.id}/><select name="status" defaultValue={item.status} aria-label={`Status for ${item.title}`}><option value="open">open</option><option value="in_progress">in progress</option><option value="blocked">blocked</option><option value="done">done</option></select><select name="assigned_user" defaultValue="" aria-label={`Assignee for ${item.title}`}><option value="">Keep assignee</option>{options.users.map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select><button aria-label={`Update ${item.title}`}>Update</button></form></article>)}</div>)}</section>
  {items.length===0&&<div className="empty-state"><IconGitBranch/><strong>No queue items</strong><p>No department queue items match this filter.</p></div>}
 </div>
}
